---
#
# Ansible managed
#
repository:
  description: Ansible role for installing and configuring victoriametrics storage backend
  homepage: https://buluma.github.io/
  topics: system, network, linux, monitoring, prometheus, node, exporter, ansible, molecule, tox, playbook, hacktoberfest
