---
#
# Ansible managed
#
repository:
  description: Deploy [victoriametrics](https://victoriametrics.com/) monitoring system.
  homepage: https://buluma.github.io/
  topics: vmutils, victoriametrics, prometheus, monitoring, ansible, molecule, tox, playbook, hacktoberfest
