---
- name: restart victoriametrics
  systemd:
    daemon_reload: true
    name: victoriametrics
    state: restarted
  become: true
  tags: victoriametrics

- name: reload victoriametrics
  systemd:
    name: victoriametrics
    state: reloaded
  become: true
  tags: victoriametrics