---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: buluma.bootstrap
    - role: buluma.python_pip
    # - role: buluma.ca
    - role: buluma.ca_certificates
    - role: buluma.victoriametrics
